In [1]:
from langchain_community.document_loaders import PyPDFLoader
pdf_path = "Saravana_Kumar_T_Resume.pdf"

loader = PyPDFLoader(pdf_path)
documents = loader.load()

In [7]:
print(documents[1])

page_content='Project Executive  |  DHAN Foundation, Chennai
November 2020 – March 2024
Management Information System (MIS) | Managing 100+ Self Help Groups
• Monitored financial indicators of 100+ Self Help Groups using SQL queries, producing regular MIS reports.
• Generated analytical reports to assess performance indicators including overdue rates, NPA, credit linkages,
and insurance metrics.
• Streamlined data reporting workflows reducing manual effort and improving accuracy of financial
dashboards.
EDUCATION

B.Sc. Computer Science – First Class  |  Dr. Zakir Husain College
2015 – 2018
CERTIFICATIONS

• Foundation Level in Programming and Data Science – Indian Institute of Technology, Madras (IITM)
• Master Data Science Program – GUVI (IIT Madras)
KEY PROJECTS

Pre-Login Check Application (BRE Engine – Applied Patent)
Streamlit • CIBIL API • CRIF API • Python • AWS • Streamlit  |  Award: Project of the Year
• Automated credit eligibility validation at pre-login stage, drastically cutting loan sanction TAT and improving
operational efficiency.
• Patent Number (202641074634) can be verified at -
https://iprsearch.ipindia.gov.in/PublicSearch/PublicationSearch/ApplicationStatus
Customer Behaviour Prediction Model
Python • Scikit-learn • EDA • AWS EC2
• Built ML model predicting customer likelihood to take a loan using CIBIL tradeline data, enabling proactive
sales targeting..' metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 1, 'page_label': '2'}

In [14]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=300
)

docs = splitter.split_documents(documents)

print(f"Created {len(docs)} chunks")

Created 7 chunks

In [15]:
docs[0].page_content

'SARAVANA KUMAR T \nData Analyst | ML Engineer | AI Developer \nChennai, India  |  +91-8940574870  |  saravanakumar2751@gmail.com \nPROFESSIONAL SUMMARY \n \nResults-driven Data Analyst and ML Engineer with 4.5+ years of experience delivering data-driven solutions \nacross fintech and development sectors. Proficient in Python, SQL, AWS, and Power BI. Proven track record in \nbuilding machine learning models, automating workflows, architecting BI dashboards, and leading cross-\nfunctional teams.  \nTECHNICAL SKILLS \n \nLanguages & Querying:  Python, MySQL, PostgreSQL \nCloud & Data Engineering:  AWS (EC2, Redshift, Glue Jobs), DBeaver \nVisualization & Reporting:  Power BI, Streamlit, MS Excel, MS PowerPoint \nMachine Learning & AI:  EDA, Feature Engineering, Scikit-learn, Deep Learning, LangChain, CrewAI, Vertex AI \nAPIs & Integration:  CIBIL API, CRIF API, Vertex AI API, Django, REST APIs, FAST APIs Bank Partner API \nIntegration \nPROFESSIONAL EXPERIENCE'

In [16]:
docs[1].page_content

'Machine Learning & AI:  EDA, Feature Engineering, Scikit-learn, Deep Learning, LangChain, CrewAI, Vertex AI \nAPIs & Integration:  CIBIL API, CRIF API, Vertex AI API, Django, REST APIs, FAST APIs Bank Partner API \nIntegration \nPROFESSIONAL EXPERIENCE \n \nData Analyst  |  Muthoot Fincorp Ltd, Chennai \nNovember 2024 – Present \nDTCE – Digital Transformation & Customer Experience | Team Lead – UI Development \n• Developed the Muthoot Fincorp Banking Assistant API utilizing Vertex AI (Gemini 2.5 Flash) and FastAPI to \ndeploy a conversational chatbot that delivers highly concise, automated customer account summaries. \n• Developed a Streamlit application (Pre-Login Check / BRE engine) leveraging CIBIL and CRIF APIs to \nautomate credit eligibility checks, significantly reducing the TAT (Turnaround Time) from loan application \nlogin to sanction (Applied Patent in progress). \n• Led the UI team within the DTCE unit, overseeing application development and data presentation standards'

In [17]:
from langchain_community.vectorstores import FAISS
from langchain_google_genai import GoogleGenerativeAIEmbeddings
embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-2"
)

# --------------------------------------
# STEP 4: Create Vector Database
# --------------------------------------

vector_store = FAISS.from_documents(
    docs,
    embeddings
)

In [19]:
print(vector_store)

<langchain_community.vectorstores.faiss.FAISS object at 0x134525190>

In [20]:
import pandas as pd
from IPython.display import display

# --------------------------------------
# STEP 4: Create Vector Database (Your existing code)
# --------------------------------------
# vector_store = FAISS.from_documents(docs, embeddings)

# --------------------------------------
# STEP 5: Visualize the Vector Store in Jupyter
# --------------------------------------

# LangChain's FAISS implementation stores the original text chunks and metadata 
# inside the 'docstore' attribute. We access its hidden dictionary (_dict).
docstore_data = vector_store.docstore._dict

# Initialize an empty list to gather the extracted data
extracted_rows = []

# Iterate through the docstore dictionary to extract the ID, content, and metadata
for doc_id, doc_object in docstore_data.items():
    extracted_rows.append({
        "Document ID": doc_id,
        "Page Content": doc_object.page_content,
        "Metadata": doc_object.metadata
    })

# Convert the list of dictionaries into a Pandas DataFrame for tabular visualization
df_vector_store = pd.DataFrame(extracted_rows)

# The display() function renders the DataFrame as a formatted, interactive table in ipynb
display(df_vector_store)

# --------------------------------------
# OPTIONAL: Viewing the actual Embedding Vectors (Numbers)
# --------------------------------------
# If you want to see the raw array of numerical embeddings (the vectors themselves),
# you can access the underlying FAISS index.

# Get the total number of vectors stored
total_vectors = vector_store.index.ntotal
print(f"\nTotal vectors in the index: {total_vectors}")

# Reconstruct and print the raw numerical vector for the first item (Index 0)
# Note: This will be a very long array of floating-point numbers
if total_vectors > 0:
    first_vector = vector_store.index.reconstruct(0)
    print("\nRaw numerical embedding for the first chunk (truncated):")
    print(first_vector[:10], "... [array continues]")

,Document ID,Page Content,Metadata
0,23190b13-3287-4a18-afbe-40582e7cf417,SARAVANA KUMAR T \nData Analyst | ML Engineer ...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
1,36e21aaa-4167-4ef5-b08f-bbf7a03322ac,"Machine Learning & AI: EDA, Feature Engineeri...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
2,c88ffdf4-8250-4fb6-98e1-56954d0ba30e,"automate credit eligibility checks, significan...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
3,ee0b4c56-e3de-4756-aaba-fc8b47f41073,"performance, overdue rates, and sanction metri...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
4,2435f782-0900-44f4-9207-4d14d43e56b4,targeting and improving conversion rates. \n• ...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
5,ea229eb3-57a9-4e1e-84e2-547fe9855f04,"Project Executive | DHAN Foundation, Chennai...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
6,799c51fe-3c2c-4ee8-a43c-b9d701aa7e51,• Master Data Science Program – GUVI (IIT Madr...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."

Total vectors in the index: 7

Raw numerical embedding for the first chunk (truncated):
[ 0.00012303  0.01336966 -0.02089177  0.00653479  0.01807619 -0.012443
 -0.02641504  0.00344779 -0.00197114 -0.0620777 ] ... [array continues]

In [22]:
display(df_vector_store)

,Document ID,Page Content,Metadata
0,23190b13-3287-4a18-afbe-40582e7cf417,SARAVANA KUMAR T \nData Analyst | ML Engineer ...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
1,36e21aaa-4167-4ef5-b08f-bbf7a03322ac,"Machine Learning & AI: EDA, Feature Engineeri...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
2,c88ffdf4-8250-4fb6-98e1-56954d0ba30e,"automate credit eligibility checks, significan...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
3,ee0b4c56-e3de-4756-aaba-fc8b47f41073,"performance, overdue rates, and sanction metri...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
4,2435f782-0900-44f4-9207-4d14d43e56b4,targeting and improving conversion rates. \n• ...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
5,ea229eb3-57a9-4e1e-84e2-547fe9855f04,"Project Executive | DHAN Foundation, Chennai...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
6,799c51fe-3c2c-4ee8-a43c-b9d701aa7e51,• Master Data Science Program – GUVI (IIT Madr...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."

In [23]:
df_vector_store

,Document ID,Page Content,Metadata
0,23190b13-3287-4a18-afbe-40582e7cf417,SARAVANA KUMAR T \nData Analyst | ML Engineer ...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
1,36e21aaa-4167-4ef5-b08f-bbf7a03322ac,"Machine Learning & AI: EDA, Feature Engineeri...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
2,c88ffdf4-8250-4fb6-98e1-56954d0ba30e,"automate credit eligibility checks, significan...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
3,ee0b4c56-e3de-4756-aaba-fc8b47f41073,"performance, overdue rates, and sanction metri...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
4,2435f782-0900-44f4-9207-4d14d43e56b4,targeting and improving conversion rates. \n• ...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
5,ea229eb3-57a9-4e1e-84e2-547fe9855f04,"Project Executive | DHAN Foundation, Chennai...","{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."
6,799c51fe-3c2c-4ee8-a43c-b9d701aa7e51,• Master Data Science Program – GUVI (IIT Madr...,"{'producer': 'PyPDF', 'creator': 'Microsoft Wo..."

In [24]:
docstore_data

{'23190b13-3287-4a18-afbe-40582e7cf417': Document(id='23190b13-3287-4a18-afbe-40582e7cf417', metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 0, 'page_label': '1'}, page_content='SARAVANA KUMAR T \nData Analyst | ML Engineer | AI Developer \nChennai, India  |  +91-8940574870  |  saravanakumar2751@gmail.com \nPROFESSIONAL SUMMARY \n \nResults-driven Data Analyst and ML Engineer with 4.5+ years of experience delivering data-driven solutions \nacross fintech and development sectors. Proficient in Python, SQL, AWS, and Power BI. Proven track record in \nbuilding machine learning models, automating workflows, architecting BI dashboards, and leading cross-\nfunctional teams.  \nTECHNICAL SKILLS \n \nLanguages & Querying:  Python, MySQL, PostgreSQL \nCloud & Data Engineering:  AWS (EC2, Redshift, Glue Jobs), DBeaver \nVisualization & Reporting:  Power BI, Streamlit, MS Excel, MS PowerPoint \nMachine Learning & AI:  EDA, Feature Engineering, Scikit-learn, Deep Learning, LangChain, CrewAI, Vertex AI \nAPIs & Integration:  CIBIL API, CRIF API, Vertex AI API, Django, REST APIs, FAST APIs Bank Partner API \nIntegration \nPROFESSIONAL EXPERIENCE'),
 '36e21aaa-4167-4ef5-b08f-bbf7a03322ac': Document(id='36e21aaa-4167-4ef5-b08f-bbf7a03322ac', metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 0, 'page_label': '1'}, page_content='Machine Learning & AI:  EDA, Feature Engineering, Scikit-learn, Deep Learning, LangChain, CrewAI, Vertex AI \nAPIs & Integration:  CIBIL API, CRIF API, Vertex AI API, Django, REST APIs, FAST APIs Bank Partner API \nIntegration \nPROFESSIONAL EXPERIENCE \n \nData Analyst  |  Muthoot Fincorp Ltd, Chennai \nNovember 2024 – Present \nDTCE – Digital Transformation & Customer Experience | Team Lead – UI Development \n• Developed the Muthoot Fincorp Banking Assistant API utilizing Vertex AI (Gemini 2.5 Flash) and FastAPI to \ndeploy a conversational chatbot that delivers highly concise, automated customer account summaries. \n• Developed a Streamlit application (Pre-Login Check / BRE engine) leveraging CIBIL and CRIF APIs to \nautomate credit eligibility checks, significantly reducing the TAT (Turnaround Time) from loan application \nlogin to sanction (Applied Patent in progress). \n• Led the UI team within the DTCE unit, overseeing application development and data presentation standards'),
 'c88ffdf4-8250-4fb6-98e1-56954d0ba30e': Document(id='c88ffdf4-8250-4fb6-98e1-56954d0ba30e', metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 0, 'page_label': '1'}, page_content='automate credit eligibility checks, significantly reducing the TAT (Turnaround Time) from loan application \nlogin to sanction (Applied Patent in progress). \n• Led the UI team within the DTCE unit, overseeing application development and data presentation standards \nacross the department. \n• Developed advanced chatbot Proof of Concepts (POCs) integrating LangChain with locally hosted LLMs \n(Ollama, Gemma); built custom Retrieval-Augmented Generation (RAG) pipelines to evaluate local inference \nlimits, multi-agent logic, and prompt orchestration. \n• Architected and built end-to-end dashboards for business stakeholders to monitor KPIs including credit \nperformance, overdue rates, and sanction metrics. \n• Conducted in-depth data analysis using Python (Jupyter Notebooks) for exploratory data analysis, feature \nengineering, and financial reporting. \n• Managed multiple partner bank API integrations for automated data ingestion and processing.'),
 'ee0b4c56-e3de-4756-aaba-fc8b47f41073': Document(id='ee0b4c56-e3de-4756-aaba-fc8b47f41073', metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 0, 'page_label': '1'}, page_content='performance, overdue rates, and sanction metrics. \n• Conducted in-depth data analysis using Python (Jupyter Notebooks) for exploratory data analysis, feature \nengineering, and financial reporting. \n• Managed multiple partner bank API integrations for automated data ingestion and processing. \n• Engineered AWS pipelines using Redshift (stored procedures), EC2, and Glue Jobs for mail automation and \njob scheduling. \n• Handled large-scale datasets (CIBIL tradelines) to generate financial insights that drive credit risk and \nbusiness decisions. \n• Built a machine learning model to predict customer loan-taking likelihood, enabling proactive customer \ntargeting and improving conversion rates. \n• Performed regular data quality monitoring and sanity checks to maintain data integrity across systems. \n \nKey Achievements \n• Won Project of the Year for Pre-Login Check Application – recognized for measurable impact on reducing \nloan processing TAT.'),
 '2435f782-0900-44f4-9207-4d14d43e56b4': Document(id='2435f782-0900-44f4-9207-4d14d43e56b4', metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 0, 'page_label': '1'}, page_content='targeting and improving conversion rates. \n• Performed regular data quality monitoring and sanity checks to maintain data integrity across systems. \n \nKey Achievements \n• Won Project of the Year for Pre-Login Check Application – recognized for measurable impact on reducing \nloan processing TAT. \n• Awarded Muthoot Blue Champion – internal recognition for outstanding contribution to digital transformation \ninitiatives.'),
 'ea229eb3-57a9-4e1e-84e2-547fe9855f04': Document(id='ea229eb3-57a9-4e1e-84e2-547fe9855f04', metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 1, 'page_label': '2'}, page_content='Project Executive  |  DHAN Foundation, Chennai \nNovember 2020 – March 2024 \nManagement Information System (MIS) | Managing 100+ Self Help Groups \n• Monitored financial indicators of 100+ Self Help Groups using SQL queries, producing regular MIS reports. \n• Generated analytical reports to assess performance indicators including overdue rates, NPA, credit linkages, \nand insurance metrics. \n• Streamlined data reporting workflows reducing manual effort and improving accuracy of financial \ndashboards. \nEDUCATION \n \nB.Sc. Computer Science – First Class  |  Dr. Zakir Husain College \n2015 – 2018 \nCERTIFICATIONS \n \n• Foundation Level in Programming and Data Science – Indian Institute of Technology, Madras (IITM) \n• Master Data Science Program – GUVI (IIT Madras) \nKEY PROJECTS \n \nPre-Login Check Application (BRE Engine – Applied Patent)  \nStreamlit • CIBIL API • CRIF API • Python • AWS • Streamlit  |  Award: Project of the Year'),
 '799c51fe-3c2c-4ee8-a43c-b9d701aa7e51': Document(id='799c51fe-3c2c-4ee8-a43c-b9d701aa7e51', metadata={'producer': 'PyPDF', 'creator': 'Microsoft Word', 'creationdate': '2026-06-20T00:47:20+00:00', 'author': 'Un-named', 'moddate': '2026-06-20T00:47:20+00:00', 'source': 'Saravana_Kumar_T_Resume.pdf', 'total_pages': 2, 'page': 1, 'page_label': '2'}, page_content='• Master Data Science Program – GUVI (IIT Madras) \nKEY PROJECTS \n \nPre-Login Check Application (BRE Engine – Applied Patent)  \nStreamlit • CIBIL API • CRIF API • Python • AWS • Streamlit  |  Award: Project of the Year \n• Automated credit eligibility validation at pre-login stage, drastically cutting loan sanction TAT and improving \noperational efficiency. \n• Patent Number (202641074634) can be verified at - \nhttps://iprsearch.ipindia.gov.in/PublicSearch/PublicationSearch/ApplicationStatus \nCustomer Behaviour Prediction Model \nPython • Scikit-learn • EDA • AWS EC2 \n• Built ML model predicting customer likelihood to take a loan using CIBIL tradeline data, enabling proactive \nsales targeting..')}